# Generated by Django 2.0.2 on 2022-04-30 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendenceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=0, verbose_name='是否出勤')),
                ('student_name', models.CharField(max_length=32, verbose_name='学生姓名')),
                ('class_name', models.CharField(max_length=32, verbose_name='课程名称')),
            ],
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='课程开始时间')),
                ('end_time', models.DateTimeField(verbose_name='课程结束时间')),
                ('user', models.CharField(max_length=32, verbose_name='使用者')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='课程名称')),
                ('credit', models.IntegerField(default=2, verbose_name='课程学分')),
                ('start_time', models.DateTimeField(verbose_name='课程开始时间')),
                ('end_time', models.DateTimeField(verbose_name='课程结束时间')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='学院名称')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='地点名称')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('age', models.IntegerField(default=None, verbose_name='年龄')),
                ('phone', models.IntegerField(default=None, verbose_name='电话')),
                ('type', models.SmallIntegerField(choices=[(2, '教师'), (1, '管理员'), (3, '学生')], verbose_name='用户类型')),
                ('number', models.CharField(max_length=32, verbose_name='账号')),
                ('password', models.CharField(max_length=32, verbose_name='姓名')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Department', verbose_name='所属学院')),
            ],
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.PlaceInfo', verbose_name='上课地点'),
        ),
        migrations.AddField(
            model_name='attendenceinfo',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.CourseInfo', verbose_name='课程号'),
        ),
        migrations.AddField(
            model_name='attendenceinfo',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='学生号'),
        ),
    ]
